services:
  web:
    build: .
    command: gunicorn --workers=3 --timeout=120 --bind 0.0.0.0:8000 config.wsgi --reload
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - DJANGO_SECRET_KEY=''
      - EMAIL_BACKEND=''
      - EMAIL_HOST=''
      - EMAIL_PORT=587
      - EMAIL_HOST_USER =''
      - EMAIL_HOST_PASSWORD=''
      - EMAIL_USE_TLS=True
      - DJANGO_SUPERUSER_USERNAME=''
      - DJANGO_SUPERUSER_EMAIL=''
      - DJANGO_SUPERUSER_PASSWORD=''